SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE reservation;
TRUNCATE TABLE review;
TRUNCATE TABLE suspension;
TRUNCATE TABLE session;
TRUNCATE TABLE room;
TRUNCATE TABLE class_type;
TRUNCATE TABLE user;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
